# Generated by Django 3.0.4 on 2020-07-04 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0006_auto_20180328_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='proje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, choices=[('Arts, Crafts & Sewing', 'Arts, Crafts & Sewing'), ('Automotive', 'Automotive'), ('Baby Products', 'Baby Products'), ('Beauty & Personal Care', 'Beauty & Personal Care'), ('Books', 'Books'), ('Cell Phones & Accessories', 'Cell Phones & Accessories'), ('Clothing, Shoes & Jewelry', 'Clothing, Shoes & Jewelry'), ('Collectibles & Fine Art', 'Collectibles & Fine Art'), ('Electronics', 'Electronics'), ('Grocery & Gourmet Food', 'Grocery & Gourmet Food'), ('Health & Household', 'Health & Household'), ('Home & Kitchen', 'Home & Kitchen'), ('Industrial & Scientific', 'Industrial & Scientific'), ('Movies & TV', 'Movies & TV'), ('Patio, Lawn & Garden', 'Patio, Lawn & Garden'), ('Pet Supplies', 'Pet Supplies'), ('Software', 'Software'), ('Sports & Outdoors', 'Sports & Outdoors'), ('Tools & Home Improvement', 'Tools & Home Improvement'), ('Toys & Games', 'Toys & Games'), ('Video Games', 'Video Games')], max_length=25)),
                ('product_code', models.TextField(blank=True, verbose_name='Asin or upc *')),
                ('product_type', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Bundle', 'Bundle'), ('Glass', 'Glass'), ('Hazardous', 'Hazardous'), ('Order Fulfillment', 'Order Fulfillment')], max_length=25)),
                ('sku', models.TextField(blank=True, verbose_name='Quantity *')),
                ('location_box', models.CharField(blank=True, choices=[('URM1', 'URI Prep & Ship - Montgomery,AL')], max_length=25)),
                ('sales_channel', models.CharField(blank=True, choices=[('Amazon', 'Amazon'), ('eBay', 'eBay')], max_length=25)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
