# Generated by Django 3.0.4 on 2020-07-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_proje'),
    ]

    operations = [
        migrations.AddField(
            model_name='proje',
            name='quantity',
            field=models.TextField(blank=True, verbose_name='Quantity *'),
        ),
        migrations.AlterField(
            model_name='proje',
            name='sku',
            field=models.TextField(blank=True, verbose_name='Sku (if empty, automatically generated)'),
        ),
    ]
